### ISSUE TITLE
Easy way to implement generic Item/Block Class for armor/tools

### ISSUE THREAD

**Issue by J3FF97** [pahimar/LetsModReboot#14]
More of a question than an Issue, but I was wondering if there is an easy way to have a class like ItemLMRB (or ItemEE for that matter) for tools and armor. I've been fooling around but haven't been able to find a good way of doing it. 
Also, Pahimar, congrats on the little girl ^.^ Take it easy and enjoy the time you'll spend together~!

**Comment by Skyamoeba** [comment]
Ok don't know if this will help you or not but I think I have managed what you were asking.

I used this as a rough guide as I did not know how to get tools in minecraft at all: http://www.minecraftforum.net/forums/mapping-and-modding/mapping-and-modding-tutorials/1571559-1-7-2-source-code-forge-modding-tutorials

And managed to do this as a result so take a look at my code and see if anything there helps.

 I have labeled everything I did with "Adding a Pickaxe" so it should be easy to find.

Link straight there: https://github.com/UKLoneWolf/LWLetsModReboot/tree/master/src/main/java/com/uklonewolf/ukletsmodreboot

**Comment by J3FF97** [comment]
Thanks for responding. I have all the code necessary, I mean, the mod I asked this for is out :P 
I'm not sure how to implement the code you send me, and after some more looking around, Since tools and armor all extend a different class I think it is not possible to have a generic itemtool or itemarmor class for your mod. Or at least not that I can think of at this moment. Closing this issue (which wasnt an issue at all :P ) because I think it isn't really that relevant atm.

**Comment by arideus101** [comment]
You can have a generic ItemArmor class, in fact I would recommend it unless
you want the helmet to boost speed and the legs to boost health, you just
have all the armor parts being a "helmet = new modArmorSet();"

On Sat, Aug 2, 2014 at 6:38 AM, Jefri notifications@github.com wrote:

> Thanks for responding. I have all the code necessary, I mean, the mod I
> asked this for is out :P
> I'm not sure how to implement the code you send me, and after some more
> looking around, Since tools and armor all extend a different class I think
> it is not possible to have a generic itemtool or itemarmor class for your
> mod. Or at least not that I can think of at this moment. Closing this issue
> (which wasnt an issue at all :P ) because I think it isn't really that
> relevant atm.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pahimar/LetsModReboot/issues/14#issuecomment-50959689
> .

## 

from jason doyle

**Comment by ghost** [comment]
Look at pahimars ModJam4 entry, on teampapayamar, it has a 'generic' armor class
