### ISSUE TITLE
Issue Downloading

### ISSUE THREAD

**Issue by UnknownLuck** [pahimar/LetsModReboot#19]
Ok, so i was trying to set up the workspace. I had put in "gradlew setupDecompWorkspace" and it got to a certain point of the download process and it stopped. It said:

The assetDir is deprecated!  Use runDir instead! runDir set to eclipse/assets/..

---

 Powered By MCP:
 http://mcp.ocean-labs.de/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : unknown

---

:extractMcpData
:getVersionJson
:extractUserDev
:genSrgs SKIPPED
:extractNatives
:getAssetsIndex
:getAssets
:makeStart
Download http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.1/scala
-library-2.11.1.jar

> # Building 35% > :makeStart > 16 KB/5.28 MB downloaded
> 
> This is where it got stuck.A little help please?

**Comment by TheCricket** [comment]
I will say this first then fix your problem. You are going to have a horrible time modding if you do not understand reports logs and how they work, you should have a good understanding of this as crash reports will be your best friend. Now onto the "problem". There isn't one you just have a really really slow computer and it will take a long time for you. Next time pastebin please, also a friend.

**Comment by UnknownLuck** [comment]
Ok thanks i will try!
