### ISSUE TITLE
Propagate version changes

### ISSUE THREAD

**Issue by jtanguy** [pahimar/LetsModReboot#5]
The version number change has not been propagated to the `Reference` class and the `mcmod.info` file. Maybe extract the version from the build.gradle file ?

**Comment by pahimar** [comment]
This was planned as part of the Advanced Build Script tutorial, but you are correct - I missed updating this :)

**Comment by porkminer** [comment]
I assume he is going to use a build.properties file and variable replacement in the build.gradle in his advanced tutorial. Like he does with ee3.

**Comment by jtanguy** [comment]
Yes I presume. For now, the problem is fixed in 5b5ae21a8ea10e756d06fbe8275ee94ea4c3842d and can be closed.
