### ISSUE TITLE
Mod Config GUI

### ISSUE THREAD

**Issue by Hurr1caneAlpha** [pahimar/LetsModReboot#9]
Well, first off, I apologise if I am posting this in the wrong place;I am new to Github. So, I've been following along to Let's Mod Reboot, and I just finished episode 7.5. However, I have just noticed something.

My GUI for the Mod doesn't show up in the Mods screen. Underneath the Forge ones, it says Config, and Disable. When I click on Let's Mod Reboot, nothing appears. My code is on my Github page.

Once again, I apologise if this is posted in the wrong place.

**Comment by Hurr1caneAlpha** [comment]
Also, a few of my friends who are following along with Let's Mod Reboot have also came across this issue, and between us, we're not sure where we are going wrong.

**Comment by ScruffyRules** [comment]
Yeah this is the wrong place.
Also I did this once but I forgot how I fixed it. Dx

**Comment by porkminer** [comment]
Check your mcmof.info file. If it isn't correct then you won't get anything.

**Comment by ScruffyRules** [comment]
Oh thanks @porkminer for giving me what's wrong, You've put your mcmod.info file 2 packages down from where it should be.

**Comment by Hurr1caneAlpha** [comment]
Okay, that's it working! Thanks for the help guys!
